"""Public optimization package contract."""

from typing import get_type_hints

import whetstone.optimization as optimization
from whetstone.optimization import (
    EffectAuthoritySchemaMismatchError,
    EvaluationBinding,
    EvaluationService,
    IntentResolution,
    IssuedToolCallConflictError,
    OptimizationHarness,
    Reward,
    RewardPolicy,
    RewardRef,
    TemplateRenderContract,
    TemplateRenderKind,
    ToolAdmissionSchemaMismatchError,
    tool_effect_request,
)

_PUBLIC_API = {
    "ADAPTER_CHECKPOINT_SCHEMA",
    "CANDIDATE_IDENTITY_SCHEMA",
    "CANDIDATE_IDENTITY_SCHEMA_VERSION",
    "CANDIDATE_RECORD_SCHEMA",
    "EVALUATION_BINDING_SCHEMA",
    "EVALUATION_BINDING_SCHEMA_VERSION",
    "EVALUATION_EVIDENCE_SCHEMA",
    "EVALUATION_FAILURE_SCHEMA",
    "EVAL_CONFIG_RECORD_SCHEMA",
    "EVAL_CONFIG_SCHEMA",
    "GLOBAL_CAPACITY_SCOPE_ID",
    "INTENT_RESOLUTION_SCHEMA",
    "INTENT_RESOLUTION_SCHEMA_VERSION",
    "MUTATION_FIELD",
    "OPTIMIZATION_RESULT_SCHEMA",
    "OPTIMIZATION_RUN_SCHEMA",
    "OPTIMIZATION_RUN_SCHEMA_VERSION",
    "PROPOSER_CONFIG_SCHEMA",
    "PROPOSER_CONFIG_SCHEMA_VERSION",
    "REWARD_POLICY_SCHEMA",
    "REWARD_POLICY_SCHEMA_VERSION",
    "REWARD_SCHEMA",
    "RUN_CAPACITY_SUBJECT_SCHEMA",
    "STEP_CAPACITY_SUBJECT_SCHEMA",
    "STEP_REQUEST_SCHEMA",
    "STEP_RESULT_SCHEMA",
    "TOOL_CALL_ENTRY_SCHEMA",
    "TOOL_CALL_SCHEMA",
    "TOOL_CONFIG_SCHEMA",
    "TOOL_CONFIG_SCHEMA_VERSION",
    "TOOL_DEFINITION_SCHEMA",
    "TOOL_DEFINITION_SCHEMA_VERSION",
    "TOOL_RESULT_SCHEMA",
    "AcquireOutcome",
    "AcquireResult",
    "AdapterCheckpoint",
    "AdapterOutput",
    "AdapterRegistry",
    "BudgetDelta",
    "BudgetState",
    "Candidate",
    "CandidateRef",
    "ContentHash",
    "DiffCheckError",
    "EffectAuthority",
    "EffectAuthorityError",
    "EffectAuthoritySchemaMismatchError",
    "EffectBusyError",
    "EffectLease",
    "EffectRecoveryRequiredError",
    "EffectRequest",
    "EffectRequestConflictError",
    "EffectTerminal",
    "EvalConfigRef",
    "EvaluatingToolExecutor",
    "EvaluationBinding",
    "EvaluationIntent",
    "EvaluationService",
    "ExecutionEnvironmentFingerprint",
    "FakeProposerTransport",
    "FiniteFloat",
    "IdentityHash",
    "IdentityOptimizerAdapter",
    "IdentityRef",
    "ImmutableJsonObject",
    "ImmutableJsonValue",
    "IntentOutcome",
    "IntentResolution",
    "IssuedToolCallConflictError",
    "LeaseMaintenance",
    "MappingAdapterRegistry",
    "MissingDataPolicy",
    "NonEmptyId",
    "NonNegativeInt",
    "OfficialRewardError",
    "OpaqueKey",
    "OptimizationHarness",
    "OptimizationProposal",
    "OptimizationResult",
    "OptimizationResultConflictError",
    "OptimizationRun",
    "OptimizationRunConflictError",
    "OptimizationRunRef",
    "OptimizationStepRequest",
    "OptimizationStepRequestRef",
    "OptimizationStepResult",
    "OptimizationStepResultRef",
    "OptimizerAdapter",
    "OutputContract",
    "ProposalDraft",
    "ProposalRequest",
    "ProposalValidationError",
    "ProposerConfig",
    "ProposerTransport",
    "RefusalClass",
    "ReplayPolicy",
    "ResolutionClass",
    "ResolutionDetail",
    "Reward",
    "RewardInputCitation",
    "RewardPolicy",
    "RewardRef",
    "RewardTerm",
    "RuntimeToolHandle",
    "StaleLeaseError",
    "StepKind",
    "StepMode",
    "StepResultConflictError",
    "StepStatus",
    "TemplateRenderContract",
    "TemplateRenderKind",
    "TerminalConflictError",
    "TerminalFailure",
    "TerminalOutcome",
    "ToolAdmissionAuthority",
    "ToolAdmissionSchemaMismatchError",
    "ToolCall",
    "ToolCallRef",
    "ToolCallState",
    "ToolCallStore",
    "ToolCallStoreConflictError",
    "ToolCallStoreEntry",
    "ToolCapacity",
    "ToolCapacityBinding",
    "ToolCapacityScope",
    "ToolConfig",
    "ToolConfigRef",
    "ToolDefinition",
    "ToolDefinitionRef",
    "ToolEvaluation",
    "ToolEvaluationError",
    "ToolEvaluator",
    "ToolEvidence",
    "ToolExecutionBusyError",
    "ToolExecutionConflictError",
    "ToolExecutionRecoveryRequiredError",
    "ToolExecutor",
    "ToolRefusal",
    "ToolResult",
    "ToolResultRef",
    "ToolValidationError",
    "TypedRef",
    "apply_reward_policy",
    "candidate_from_draft",
    "candidate_reference",
    "canonical_json_equal",
    "compute_identity_hash",
    "diff_check",
    "eval_config_reference",
    "freeze_json_object",
    "optimization_result_reference",
    "optimization_run_reference",
    "require_full_hash",
    "reward_reference",
    "step_request_reference",
    "step_result_reference",
    "tool_call_reference",
    "tool_capacity_binding",
    "tool_config_reference",
    "tool_definition_reference",
    "tool_effect_request",
    "tool_result_reference",
    "typed_ref_for_record",
    "validate_candidate_template",
}

_CANONICAL_IMPORTS = {
    "EffectAuthoritySchemaMismatchError": EffectAuthoritySchemaMismatchError,
    "EvaluationBinding": EvaluationBinding,
    "IssuedToolCallConflictError": IssuedToolCallConflictError,
    "OptimizationHarness": OptimizationHarness,
    "Reward": Reward,
    "RewardPolicy": RewardPolicy,
    "RewardRef": RewardRef,
    "TemplateRenderContract": TemplateRenderContract,
    "TemplateRenderKind": TemplateRenderKind,
    "ToolAdmissionSchemaMismatchError": ToolAdmissionSchemaMismatchError,
    "tool_effect_request": tool_effect_request,
}


def test_public_api_is_exact_and_unique() -> None:
    assert set(optimization.__all__) == _PUBLIC_API
    assert len(optimization.__all__) == len(_PUBLIC_API)
    assert all(hasattr(optimization, name) for name in _PUBLIC_API)


def test_canonical_capabilities_import_from_package() -> None:
    assert all(
        getattr(optimization, name) is value
        for name, value in _CANONICAL_IMPORTS.items()
    )


def test_graph_validation_protocol_stays_optimization_owned() -> None:
    hints = get_type_hints(EvaluationService.validate_resolution_graph)

    assert hints == {"resolution": IntentResolution, "return": type(None)}
    assert IntentResolution.__module__ == "whetstone.optimization.schema"
