"""Generic durable optimization contracts and harness."""

from importlib import import_module

from whetstone.optimization.adapters import (
    AdapterCheckpoint,
    AdapterOutput,
    AdapterRegistry,
    AdapterReplayPolicyMismatchError,
    IdentityOptimizerAdapter,
    MappingAdapterRegistry,
    OptimizerAdapter,
)
from whetstone.optimization.copro import (
    CoproAdapter,
    CoproAttempt,
    CoproConfig,
    CoproDriver,
    CoproFinalization,
    CoproState,
)
from whetstone.optimization.copro_control import (
    COPRO_ALGORITHM_VERSION,
    COPRO_REFERENCE_COMMIT,
    CoproControl,
    CoproInjectedDefaults,
    configure_copro,
)
from whetstone.optimization.effect_authority import (
    AcquireOutcome,
    AcquireResult,
    EffectAuthority,
    EffectAuthorityError,
    EffectAuthoritySchemaMismatchError,
    EffectLease,
    EffectRequest,
    EffectTerminal,
    LeaseMaintenance,
    ReplayPolicy,
    StaleLeaseError,
    TerminalConflictError,
    TerminalOutcome,
)
from whetstone.optimization.harness import (
    ADAPTER_CHECKPOINT_SCHEMA,
    EffectBusyError,
    EffectRecoveryRequiredError,
    EffectRequestConflictError,
    EvaluationService,
    IssuedToolCallConflictError,
    OptimizationHarness,
    OptimizationResultConflictError,
    OptimizationRunConflictError,
    StepResultConflictError,
    ToolExecutor,
)
from whetstone.optimization.identity import (
    ContentHash,
    FiniteFloat,
    IdentityHash,
    IdentityRef,
    ImmutableJsonObject,
    ImmutableJsonValue,
    NonEmptyId,
    NonNegativeInt,
    OpaqueKey,
    TerminalFailure,
    TypedRef,
    canonical_json_equal,
    compute_identity_hash,
    freeze_json_object,
    require_full_hash,
    typed_ref_for_record,
)
from whetstone.optimization.mutation import (
    MUTATION_FIELD,
    DiffCheckError,
    ProposalValidationError,
    candidate_from_draft,
    diff_check,
    validate_candidate_template,
)
from whetstone.optimization.proposal_prompts import (
    COPRO_PROPOSAL_PROMPT_SCHEMA_TAG,
)
from whetstone.optimization.proposer import (
    PROPOSER_CONFIG_SCHEMA,
    PROPOSER_CONFIG_SCHEMA_VERSION,
    DurableProposalExecutor,
    FakeProposerTransport,
    ProposalDraft,
    ProposalExecutorDurabilityContract,
    ProposalRequest,
    ProposerConfig,
    ProposerTransport,
    ProviderProposerTransport,
    prompt_adapter_identity_hash,
)
from whetstone.optimization.reward import (
    REWARD_POLICY_SCHEMA,
    REWARD_POLICY_SCHEMA_VERSION,
    REWARD_SCHEMA,
    MissingDataPolicy,
    OfficialRewardError,
    Reward,
    RewardInputCitation,
    RewardPolicy,
    RewardRef,
    RewardTerm,
    apply_reward_policy,
    reward_reference,
)
from whetstone.optimization.schema import (
    CANDIDATE_IDENTITY_SCHEMA,
    CANDIDATE_IDENTITY_SCHEMA_VERSION,
    CANDIDATE_RECORD_SCHEMA,
    EVAL_CONFIG_RECORD_SCHEMA,
    EVALUATION_BINDING_SCHEMA,
    EVALUATION_BINDING_SCHEMA_VERSION,
    EVALUATION_EVIDENCE_SCHEMA,
    EVALUATION_FAILURE_SCHEMA,
    INTENT_RESOLUTION_SCHEMA,
    INTENT_RESOLUTION_SCHEMA_VERSION,
    OPTIMIZATION_RESULT_SCHEMA,
    OPTIMIZATION_RUN_SCHEMA,
    OPTIMIZATION_RUN_SCHEMA_VERSION,
    STEP_REQUEST_SCHEMA,
    STEP_RESULT_SCHEMA,
    BudgetDelta,
    BudgetState,
    Candidate,
    CandidateRef,
    EvalConfigRef,
    EvaluationBinding,
    EvaluationIntent,
    ExecutionEnvironmentFingerprint,
    IntentOutcome,
    IntentResolution,
    OptimizationProposal,
    OptimizationResult,
    OptimizationRun,
    OptimizationRunRef,
    OptimizationStepRequest,
    OptimizationStepRequestRef,
    OptimizationStepResult,
    OptimizationStepResultRef,
    OutputContract,
    ResolutionClass,
    ResolutionDetail,
    StepKind,
    StepMode,
    StepStatus,
    TemplateRenderContract,
    TemplateRenderKind,
    ToolEvidence,
    candidate_reference,
    eval_config_reference,
    optimization_result_reference,
    optimization_run_reference,
    step_request_reference,
    step_result_reference,
)
from whetstone.optimization.tool_eval import (
    EvaluatingToolExecutor,
    ToolEvaluation,
    ToolEvaluationError,
    ToolEvaluator,
    ToolExecutionBusyError,
    ToolExecutionConflictError,
    ToolExecutionRecoveryRequiredError,
    ToolValidationError,
)
from whetstone.optimization.tool_store import (
    TOOL_CALL_ENTRY_SCHEMA,
    ToolAdmissionAuthority,
    ToolAdmissionSchemaMismatchError,
    ToolCallState,
    ToolCallStore,
    ToolCallStoreConflictError,
    ToolCallStoreEntry,
    tool_effect_request,
)
from whetstone.optimization.tools import (
    EVAL_CONFIG_SCHEMA,
    GLOBAL_CAPACITY_SCOPE_ID,
    RUN_CAPACITY_SUBJECT_SCHEMA,
    STEP_CAPACITY_SUBJECT_SCHEMA,
    TOOL_CALL_SCHEMA,
    TOOL_CONFIG_SCHEMA,
    TOOL_CONFIG_SCHEMA_VERSION,
    TOOL_DEFINITION_SCHEMA,
    TOOL_DEFINITION_SCHEMA_VERSION,
    TOOL_RESULT_SCHEMA,
    RefusalClass,
    RuntimeToolHandle,
    ToolCall,
    ToolCallRef,
    ToolCapacity,
    ToolCapacityBinding,
    ToolCapacityScope,
    ToolConfig,
    ToolConfigRef,
    ToolDefinition,
    ToolDefinitionRef,
    ToolRefusal,
    ToolResult,
    ToolResultRef,
    tool_call_reference,
    tool_capacity_binding,
    tool_config_reference,
    tool_definition_reference,
    tool_result_reference,
)

_LAZY_MIPROV2_EXPORTS = {
    "MIPROV2_ADAPTER_KEY": "whetstone.optimization.miprov2",
    "Miprov2Adapter": "whetstone.optimization.miprov2",
    "MIPROV2_ALGORITHM_VERSION": "whetstone.optimization.miprov2_control",
    "MIPROV2_OPTUNA_VERSION": "whetstone.optimization.miprov2_control",
    "MIPROV2_PROMPT_FORMAT_ADAPTER_VERSION": (
        "whetstone.optimization.miprov2_control"
    ),
    "MIPROV2_REFERENCE_COMMIT": "whetstone.optimization.miprov2_control",
    "Miprov2AutoMode": "whetstone.optimization.miprov2_control",
    "Miprov2Control": "whetstone.optimization.miprov2_control",
    "Miprov2InjectedDefaults": "whetstone.optimization.miprov2_control",
    "configure_miprov2": "whetstone.optimization.miprov2_control",
}


def __getattr__(name: str):
    """Load the MIPROv2 facade without introducing env import cycles."""

    module_name = _LAZY_MIPROV2_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


__all__ = [
    "ADAPTER_CHECKPOINT_SCHEMA",
    "CANDIDATE_IDENTITY_SCHEMA",
    "CANDIDATE_IDENTITY_SCHEMA_VERSION",
    "CANDIDATE_RECORD_SCHEMA",
    "COPRO_ALGORITHM_VERSION",
    "COPRO_PROPOSAL_PROMPT_SCHEMA_TAG",
    "COPRO_REFERENCE_COMMIT",
    "EVALUATION_BINDING_SCHEMA",
    "EVALUATION_BINDING_SCHEMA_VERSION",
    "EVALUATION_EVIDENCE_SCHEMA",
    "EVALUATION_FAILURE_SCHEMA",
    "EVAL_CONFIG_RECORD_SCHEMA",
    "EVAL_CONFIG_SCHEMA",
    "GLOBAL_CAPACITY_SCOPE_ID",
    "INTENT_RESOLUTION_SCHEMA",
    "INTENT_RESOLUTION_SCHEMA_VERSION",
    "MIPROV2_ADAPTER_KEY",
    "MIPROV2_ALGORITHM_VERSION",
    "MIPROV2_OPTUNA_VERSION",
    "MIPROV2_PROMPT_FORMAT_ADAPTER_VERSION",
    "MIPROV2_REFERENCE_COMMIT",
    "MUTATION_FIELD",
    "OPTIMIZATION_RESULT_SCHEMA",
    "OPTIMIZATION_RUN_SCHEMA",
    "OPTIMIZATION_RUN_SCHEMA_VERSION",
    "PROPOSER_CONFIG_SCHEMA",
    "PROPOSER_CONFIG_SCHEMA_VERSION",
    "REWARD_POLICY_SCHEMA",
    "REWARD_POLICY_SCHEMA_VERSION",
    "REWARD_SCHEMA",
    "RUN_CAPACITY_SUBJECT_SCHEMA",
    "STEP_CAPACITY_SUBJECT_SCHEMA",
    "STEP_REQUEST_SCHEMA",
    "STEP_RESULT_SCHEMA",
    "TOOL_CALL_ENTRY_SCHEMA",
    "TOOL_CALL_SCHEMA",
    "TOOL_CONFIG_SCHEMA",
    "TOOL_CONFIG_SCHEMA_VERSION",
    "TOOL_DEFINITION_SCHEMA",
    "TOOL_DEFINITION_SCHEMA_VERSION",
    "TOOL_RESULT_SCHEMA",
    "AcquireOutcome",
    "AcquireResult",
    "AdapterCheckpoint",
    "AdapterOutput",
    "AdapterRegistry",
    "AdapterReplayPolicyMismatchError",
    "BudgetDelta",
    "BudgetState",
    "Candidate",
    "CandidateRef",
    "ContentHash",
    "CoproAdapter",
    "CoproAttempt",
    "CoproConfig",
    "CoproControl",
    "CoproDriver",
    "CoproFinalization",
    "CoproInjectedDefaults",
    "CoproState",
    "DiffCheckError",
    "DurableProposalExecutor",
    "EffectAuthority",
    "EffectAuthorityError",
    "EffectAuthoritySchemaMismatchError",
    "EffectBusyError",
    "EffectLease",
    "EffectRecoveryRequiredError",
    "EffectRequest",
    "EffectRequestConflictError",
    "EffectTerminal",
    "EvalConfigRef",
    "EvaluatingToolExecutor",
    "EvaluationBinding",
    "EvaluationIntent",
    "EvaluationService",
    "ExecutionEnvironmentFingerprint",
    "FakeProposerTransport",
    "FiniteFloat",
    "IdentityHash",
    "IdentityOptimizerAdapter",
    "IdentityRef",
    "ImmutableJsonObject",
    "ImmutableJsonValue",
    "IntentOutcome",
    "IntentResolution",
    "IssuedToolCallConflictError",
    "LeaseMaintenance",
    "MappingAdapterRegistry",
    "Miprov2Adapter",
    "Miprov2AutoMode",
    "Miprov2Control",
    "Miprov2InjectedDefaults",
    "MissingDataPolicy",
    "NonEmptyId",
    "NonNegativeInt",
    "OfficialRewardError",
    "OpaqueKey",
    "OptimizationHarness",
    "OptimizationProposal",
    "OptimizationResult",
    "OptimizationResultConflictError",
    "OptimizationRun",
    "OptimizationRunConflictError",
    "OptimizationRunRef",
    "OptimizationStepRequest",
    "OptimizationStepRequestRef",
    "OptimizationStepResult",
    "OptimizationStepResultRef",
    "OptimizerAdapter",
    "OutputContract",
    "ProposalDraft",
    "ProposalExecutorDurabilityContract",
    "ProposalRequest",
    "ProposalValidationError",
    "ProposerConfig",
    "ProposerTransport",
    "ProviderProposerTransport",
    "RefusalClass",
    "ReplayPolicy",
    "ResolutionClass",
    "ResolutionDetail",
    "Reward",
    "RewardInputCitation",
    "RewardPolicy",
    "RewardRef",
    "RewardTerm",
    "RuntimeToolHandle",
    "StaleLeaseError",
    "StepKind",
    "StepMode",
    "StepResultConflictError",
    "StepStatus",
    "TemplateRenderContract",
    "TemplateRenderKind",
    "TerminalConflictError",
    "TerminalFailure",
    "TerminalOutcome",
    "ToolAdmissionAuthority",
    "ToolAdmissionSchemaMismatchError",
    "ToolCall",
    "ToolCallRef",
    "ToolCallState",
    "ToolCallStore",
    "ToolCallStoreConflictError",
    "ToolCallStoreEntry",
    "ToolCapacity",
    "ToolCapacityBinding",
    "ToolCapacityScope",
    "ToolConfig",
    "ToolConfigRef",
    "ToolDefinition",
    "ToolDefinitionRef",
    "ToolEvaluation",
    "ToolEvaluationError",
    "ToolEvaluator",
    "ToolEvidence",
    "ToolExecutionBusyError",
    "ToolExecutionConflictError",
    "ToolExecutionRecoveryRequiredError",
    "ToolExecutor",
    "ToolRefusal",
    "ToolResult",
    "ToolResultRef",
    "ToolValidationError",
    "TypedRef",
    "apply_reward_policy",
    "candidate_from_draft",
    "candidate_reference",
    "canonical_json_equal",
    "compute_identity_hash",
    "configure_copro",
    "configure_miprov2",
    "diff_check",
    "eval_config_reference",
    "freeze_json_object",
    "optimization_result_reference",
    "optimization_run_reference",
    "prompt_adapter_identity_hash",
    "require_full_hash",
    "reward_reference",
    "step_request_reference",
    "step_result_reference",
    "tool_call_reference",
    "tool_capacity_binding",
    "tool_config_reference",
    "tool_definition_reference",
    "tool_effect_request",
    "tool_result_reference",
    "typed_ref_for_record",
    "validate_candidate_template",
]
